<?php

namespace Larafusion\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GenerateApiCommand extends Command
{
    protected $signature = 'larafusion:api
        {--prefix=api      : URL prefix for the API routes}
        {--middleware=      : Comma-separated middleware (default: api,auth:sanctum)}
        {--force            : Overwrite existing api/larafusion.php routes file}';

    protected $description = 'Generate a JSON REST API for all registered Larafusion resources';

    public function handle(): int
    {
        $prefix     = $this->option('prefix') ?: 'api';
        $middleware = $this->option('middleware')
            ? explode(',', $this->option('middleware'))
            : ['api', 'auth:sanctum'];

        $middlewareStr = "['" . implode("', '", $middleware) . "']";
        $routesPath    = base_path('routes/larafusion-api.php');

        if (File::exists($routesPath) && !$this->option('force')) {
            $this->error("routes/larafusion-api.php already exists. Use --force to overwrite.");
            return self::FAILURE;
        }

        $stub = <<<PHP
<?php

use Illuminate\Support\Facades\Route;
use Larafusion\Http\Controllers\Api\ResourceApiController;

/*
 * Auto-generated Larafusion REST API routes.
 * Generated by: php artisan larafusion:api
 *
 * Authentication: Laravel Sanctum (api tokens)
 * Docs: GET /{resource}/schema — returns field schema + column definitions
 */
Route::prefix('{$prefix}')
    ->middleware({$middlewareStr})
    ->name('larafusion.api.')
    ->group(function () {
        Route::get   ('/{resource}',         [ResourceApiController::class, 'index'])  ->name('index');
        Route::post  ('/{resource}',         [ResourceApiController::class, 'store'])  ->name('store');
        Route::get   ('/{resource}/schema',  [ResourceApiController::class, 'schema']) ->name('schema');
        Route::get   ('/{resource}/{id}',    [ResourceApiController::class, 'show'])   ->name('show');
        Route::put   ('/{resource}/{id}',    [ResourceApiController::class, 'update']) ->name('update');
        Route::patch ('/{resource}/{id}',    [ResourceApiController::class, 'update']) ->name('update.patch');
        Route::delete('/{resource}/{id}',    [ResourceApiController::class, 'destroy'])->name('destroy');
    });
PHP;

        File::put($routesPath, $stub);
        $this->info("API routes file created: <comment>routes/larafusion-api.php</comment>");

        // Register in bootstrap/app.php if not already
        $this->registerRoutes();

        $this->newLine();
        $this->line("Available endpoints:");
        $this->table(
            ['Method', 'URI', 'Action'],
            [
                ['GET',    "/{$prefix}/{resource}",        'List records (paginated)'],
                ['POST',   "/{$prefix}/{resource}",        'Create a record'],
                ['GET',    "/{$prefix}/{resource}/schema", 'Field schema + columns'],
                ['GET',    "/{$prefix}/{resource}/{id}",   'Show a single record'],
                ['PUT',    "/{$prefix}/{resource}/{id}",   'Update a record (full)'],
                ['PATCH',  "/{$prefix}/{resource}/{id}",   'Update a record (partial)'],
                ['DELETE', "/{$prefix}/{resource}/{id}",   'Delete a record'],
            ]
        );

        $this->newLine();
        $this->line("Add <comment>->api()</comment> to your Panel to enable the API globally.");
        $this->line("Or include <comment>routes/larafusion-api.php</comment> in bootstrap/app.php manually.");

        return self::SUCCESS;
    }

    protected function registerRoutes(): void
    {
        $appPath = base_path('bootstrap/app.php');
        if (!File::exists($appPath)) return;

        $content = File::get($appPath);
        if (str_contains($content, 'larafusion-api.php')) {
            $this->line("  Routes already registered in bootstrap/app.php");
            return;
        }

        // Insert before the closing of ->withRouting()
        $content = preg_replace(
            '/(->withRouting\([^)]*)(web:\s*__DIR__\s*\..*?\.php\')/s',
            '$1$2,' . "\n" . "        using: function () {\n"
                . "            \\Illuminate\\Support\\Facades\\Route::middleware('web')\n"
                . "                ->group(base_path('routes/larafusion-api.php'));\n"
                . "        },",
            $content
        );

        // Simpler fallback: add a require to web.php comment area
        if (!str_contains($content, 'larafusion-api.php')) {
            $webRoutesPath = base_path('routes/web.php');
            if (File::exists($webRoutesPath)) {
                $webContent = File::get($webRoutesPath);
                if (!str_contains($webContent, 'larafusion-api.php')) {
                    File::append($webRoutesPath, "\nrequire __DIR__.'/larafusion-api.php';\n");
                    $this->line("  Added require to <comment>routes/web.php</comment>");
                }
            }
        }
    }
}
