<?php

namespace Larafusion\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class IdeHelpersCommand extends Command
{
    protected $signature   = 'larafusion:ide-helpers {--path= : Output path (default: _ide_helper_larafusion.php)}';
    protected $description = 'Generate IDE helper stubs with PHPDoc for all Larafusion fluent APIs';

    public function handle(): int
    {
        $path = $this->option('path') ?: base_path('_ide_helper_larafusion.php');

        $stub = $this->buildStub();
        File::put($path, $stub);

        $this->info("IDE helper stubs written to: <comment>{$path}</comment>");
        $this->line("Add <comment>{$path}</comment> to your .gitignore if desired.");

        return self::SUCCESS;
    }

    protected function buildStub(): string
    {
        return <<<'PHP'
<?php
// @formatter:off
/**
 * Larafusion IDE helper stubs — auto-generated by `php artisan larafusion:ide-helpers`.
 * Do NOT edit by hand. Re-run the command after upgrading Larafusion.
 *
 * @see https://github.com/larafusion/larafusion
 */

namespace Larafusion {

    /**
     * @method static static make()
     * @method static id(string $id)
     * @method static path(string $path)
     * @method static domain(string $domain)
     * @method static login(bool $enabled = true)
     * @method static registration(bool $enabled = true)
     * @method static forgotPassword(bool $enabled = true)
     * @method static middleware(array $middleware)
     * @method static authMiddleware(array $middleware)
     * @method static brand(string $name, ?string $logo = null)
     * @method static brandLogo(string $url)
     * @method static darkModeBrandLogo(string $url)
     * @method static brandLogoHeight(string $height)
     * @method static favicon(string $url)
     * @method static font(string $family, ?string $weight = null)
     * @method static theme(string $name, bool $darkMode = false)
     * @method static darkMode(bool $enabled = true)
     * @method static defaultThemeMode(string $mode)
     * @method static colors(array $colors)
     * @method static topNavigation(bool $enabled = true)
     * @method static sidebarCollapsibleOnDesktop(bool $enabled = true)
     * @method static sidebarWidth(string $width)
     * @method static collapsedSidebarWidth(string $width)
     * @method static maxContentWidth(?string $width)
     * @method static breadcrumbs(bool $enabled = true)
     * @method static breadcrumbsPosition(string $position)
     * @method static topbar(bool $enabled = true)
     * @method static subNavigationPosition(string $position)
     * @method static globalSearch(bool $enabled = true)
     * @method static notifications(bool $enabled = true)
     * @method static authGuard(string $guard)
     * @method static authPasswordBroker(string $broker)
     * @method static revealablePasswords(bool $enabled = true)
     * @method static profile(bool $enabled = true)
     * @method static loginSlug(string $slug)
     * @method static registrationSlug(string $slug)
     * @method static forgotPasswordSlug(string $slug)
     * @method static resetPasswordSlug(string $slug)
     * @method static profileSlug(string $slug)
     * @method static userMenu(bool|string $positionOrEnabled = true)
     * @method static userMenuItems(array $items)
     * @method static unsavedChangesAlerts(bool $enabled = true)
     * @method static databaseTransactions(bool $enabled = true)
     * @method static strictAuthorization(bool $enabled = true)
     * @method static prefetch(bool $enabled = true)
     * @method static prefetchStrategy(string|array $strategy)
     * @method static prefetchCacheFor(string|int|array $duration)
     * @method static prefetchFlushOnNavigate(bool $flush = true)
     * @method static pagination(int $perPage)
     * @method static resources(array $classes)
     * @method static pages(array $classes)
     * @method static widgets(array $classes)
     * @method static plugins(array $classes)
     * @method static navigationItems(array $items)
     * @method static bootUsing(\Closure $callback)
     * @method static loginRateLimiting(bool|int $maxAttempts = 5, int $decayMinutes = 1)
     * @method static twoFactor(bool $enabled = true, bool $enforce = false)
     * @method static tenancy(\Closure $resolver)
     * @method static realtime(bool $enabled = true, string $channel = 'larafusion')
     * @method static api(bool $enabled = true, string $prefix = 'api', array $middleware = ['api', 'auth:sanctum'])
     */
    class Panel {}

    /**
     * @method static array form()
     * @method static \Larafusion\Tables\Table table(\Larafusion\Tables\Table $table)
     * @method static array columns()
     * @method static array actions()
     * @method static array widgets()
     * @method static bool useModalForms()
     * @method static bool exportable()
     * @method static bool importable()
     * @method static array getExportColumns()
     * @method static array getImportColumns()
     * @method static bool softDeletes()
     * @method static array getInlineEditable()
     * @method static string getModel()
     * @method static int getPerPage()
     * @method static array getSearchable()
     * @method static array getSortable()
     * @method static string getRecordLabel()
     * @method static string getNavigationIcon()
     * @method static string|null getNavigationGroup()
     * @method static int getNavigationSort()
     * @method static string|int|null getNavigationBadge()
     * @method static string getSlug()
     * @method static string getNavigationLabel()
     * @method static array getFormSchema()
     * @method static array getColumnsSchema()
     * @method static array getTableConfig()
     * @method static array getActionsSchema(?\Illuminate\Database\Eloquent\Model $record = null)
     * @method static array getCreateRules()
     * @method static array getUpdateRules(int|string $id)
     * @method static array getFlatFields()
     * @method static string getGlobalSearchTitle(\Illuminate\Database\Eloquent\Model $record)
     * @method static string|null getGlobalSearchDescription(\Illuminate\Database\Eloquent\Model $record)
     * @method static bool canViewAny()
     * @method static bool canCreate()
     * @method static bool canEdit()
     * @method static bool canDelete()
     * @method static bool canView()
     * @method static mixed scopeForTenant(mixed $query, mixed $tenant)
     * @method static array getPageProps(string $page, mixed $record = null)
     */
    class Resource {}
}

namespace Larafusion\Fields {

    /**
     * @method static static make(string $name, ?string $label = null)
     * @method string getName()
     * @method string getLabel()
     * @method array getRules()
     * @method array getClientRules()
     * @method static required(bool $required = true)
     * @method static nullable(bool $nullable = true)
     * @method static default(mixed $value)
     * @method static hint(string $text)
     * @method static helperText(string $text)
     * @method static placeholder(string $text)
     * @method static disabled(bool $disabled = true)
     * @method static readOnly(bool $readOnly = true)
     * @method static hidden(bool $hidden = true)
     * @method static columnSpan(int $span)
     * @method static columnSpanFull()
     * @method static label(string $label)
     * @method static hiddenLabel(bool $hidden = true)
     * @method static unique(string|null $table = null, string|null $column = null)
     * @method static rules(array|string $rules)
     * @method static validationAttribute(string $attribute)
     * @method static validationMessages(array $messages)
     */
    class Field {}

    /**
     * Text field.
     * @method static url(bool $enabled = true)
     * @method static tel(bool $enabled = true)
     * @method static telRegex(string $regex)
     * @method static integer(bool $enabled = true)
     * @method static numeric(bool $enabled = true)
     * @method static length(int $max)
     * @method static minLength(int $min)
     * @method static copyable(bool $enabled = true)
     * @method static trim(bool $enabled = true)
     * @method static mask(string $mask)
     * @method static autocomplete(string $value)
     * @method static datalist(array $options)
     * @method static inputMode(string $mode)
     * @method static prefix(string $text)
     * @method static suffix(string $text)
     * @method static prefixIcon(string $icon)
     * @method static suffixIcon(string $icon)
     */
    class Text extends Field {}

    /**
     * Select field.
     * @method static options(array|\Closure|string $options)
     * @method static native(bool $native = true)
     * @method static multiple(bool $enabled = true)
     * @method static searchable(bool $enabled = true)
     * @method static clearable(bool $enabled = true)
     * @method static boolean()
     * @method static disabledOptions(array $options)
     * @method static disableOptionWhen(\Closure $callback)
     * @method static minItems(int $min)
     * @method static maxItems(int $max)
     * @method static enum(string $enumClass)
     */
    class Select extends Field {}

    /**
     * File / Image upload.
     * @method static disk(string $disk)
     * @method static directory(string $path)
     * @method static multiple(bool $enabled = true)
     * @method static maxFiles(int $max)
     * @method static minFiles(int $min)
     * @method static maxSize(int $kb)
     * @method static minSize(int $kb)
     * @method static acceptedFileTypes(array $types)
     * @method static visibility(string $visibility)
     * @method static openable(bool $enabled = true)
     * @method static reorderable(bool $enabled = true)
     * @method static circular(bool $enabled = true)
     */
    class FileUpload extends Field {}
}

namespace Larafusion\Tables {

    /**
     * @method static static make()
     * @method columns(array $columns)
     * @method filters(array $filters, \Larafusion\Tables\Enums\FiltersLayout|string|null $layout = null)
     * @method recordActions(array $actions)
     * @method toolbarActions(array $actions)
     * @method striped(bool $striped = true)
     * @method heading(string $heading)
     * @method description(string $description)
     * @method emptyState(string $message, ?string $description = null, ?string $icon = null)
     * @method defaultSort(string $field, string $dir = 'asc')
     * @method filtersLayout(\Larafusion\Tables\Enums\FiltersLayout|string $layout)
     * @method filtersFormColumns(int $columns)
     * @method filtersFormWidth(string $width)
     * @method filtersFormMaxHeight(string $height)
     * @method hiddenFilterIndicators(bool $hidden = true)
     */
    class Table {}
}

namespace Larafusion\Columns {

    /**
     * @method static static make(string $name, ?string $label = null)
     * @method sortable(bool $enabled = true)
     * @method searchable(bool $enabled = true)
     * @method filterable(bool $enabled = true)
     * @method toggleable(bool $enabled = true)
     * @method hidden(bool $hidden = true)
     * @method label(string $label)
     * @method columnSpan(int $span)
     */
    class Column {}

    /**
     * @method limit(int $chars)
     * @method wrap(bool $enabled = true)
     * @method copyable(bool $enabled = true)
     * @method description(string|\Closure $text, string $position = 'below')
     * @method prefix(string $text)
     * @method suffix(string $text)
     * @method weight(string $weight)
     * @method money(string $currency = 'USD')
     * @method asBadge(bool $enabled = true)
     * @method enum(string $enumClass)
     */
    class TextColumn extends Column {}

    /**
     * @method colors(array $map)
     * @method icons(array $map)
     * @method enum(string $enumClass)
     */
    class BadgeColumn extends Column {}
}
// @formatter:on
PHP;
    }
}
